apiVersion: batch/v1
kind: CronJob
metadata:
  name: rust-weather-insights-job
spec:
  schedule: "*/1   * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rust-weather-insights
              image: saad17g/rustweatherinsights:v1
          restartPolicy: OnFailure
